const API="https://workspacehub-backend-jg13.onrender.com/api";let spaces=[],user=JSON.parse(localStorage.getItem("workspaceHubUser")||"null"),selected=null,authMode="login";
const $=id=>document.getElementById(id);function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
async function api(path,opt={}){let headers={"Content-Type":"application/json",...(opt.headers||{})};if(user?.token)headers.Authorization=`Bearer ${user.token}`;let r=await fetch(API+path,{...opt,headers}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d}
function show(id){["home","spaces","dashboard"].forEach(x=>$(x).classList.toggle("hidden",x!==id));if(id==="spaces")renderSpaces();if(id==="dashboard")renderDash();scrollTo(0,0)}
function authUI(){$("loginBtn").classList.toggle("hidden",!!user);$("logoutBtn").classList.toggle("hidden",!user)}
function openAuth(mode="login"){authMode=mode;setAuth();$("authModal").classList.remove("hidden")}function setAuth(){$("authTitle").textContent=authMode==="login"?"Sign in":"Create account";$("ltab").classList.toggle("active",authMode==="login");$("rtab").classList.toggle("active",authMode==="register");$("name").classList.toggle("hidden",authMode==="login")}
function closeM(id){$(id).classList.add("hidden")}
async function load(){try{spaces=await api("/spaces")}catch{spaces=[];toast("Start the backend to load spaces")}renderSpaces()}
function renderSpaces(){let q=$("search").value.toLowerCase(),k=$("kind").value,c=+$("capacity").value;let a=spaces.filter(s=>(!q||`${s.name} ${s.city} ${s.features.join(" ")}`.toLowerCase().includes(q))&&(!k||s.kind===k)&&(!c||s.capacity>=c));$("spaceGrid").innerHTML=a.length?a.map(s=>`<article class="card"><span class="eyebrow">${esc(s.kind)}</span><h3>${esc(s.name)}</h3><div class="muted">${esc(s.city)} · ${s.capacity} people</div><div class="tags">${s.features.map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div><div class="price">₹${s.pricePerHour}/hour</div><button class="primary" onclick="openBook('${s._id}')">Check availability</button></article>`).join(""):`<div class="panel"><h3>No spaces found</h3><p>Try another filter.</p></div>`}
function openBook(id){selected=spaces.find(s=>s._id===id);if(!user){openAuth("login");return}$("spaceName").textContent=`${selected.name} · ${selected.city}`;$("date").min=new Date().toISOString().slice(0,10);$("bookModal").classList.remove("hidden")}
$("authForm").onsubmit=async e=>{e.preventDefault();try{let path=authMode==="login"?"/auth/login":"/auth/register",body={email:$("email").value,password:$("password").value};if(authMode==="register")Object.assign(body,{name:$("name").value});let d=await api(path,{method:"POST",body:JSON.stringify(body)});user=d.user;localStorage.setItem("workspaceHubUser",JSON.stringify(user));authUI();closeM("authModal");e.target.reset();toast("Signed in successfully");show("dashboard")}catch(e){toast(e.message)}}
$("bookForm").onsubmit=async e=>{e.preventDefault();try{await api("/bookings",{method:"POST",body:JSON.stringify({spaceId:selected._id,date:$("date").value,startTime:$("start").value,endTime:$("end").value})});closeM("bookModal");e.target.reset();toast("Booking confirmed");show("dashboard")}catch(e){toast(e.message)}}
async function renderDash(){if(!user){$("dash").innerHTML=`<div class="panel"><h3>Sign in to view bookings</h3><button class="primary" onclick="openAuth()">Sign in</button></div>`;return}try{let d=await api("/dashboard");$("dash").innerHTML=`<div class="stats"><div class="stat"><span class="muted">Total bookings</span><strong>${d.bookings.length}</strong></div><div class="stat"><span class="muted">Upcoming</span><strong>${d.bookings.filter(x=>x.status==="confirmed").length}</strong></div><div class="stat"><span class="muted">Account</span><strong>Active</strong></div></div><div class="panel"><h3>My bookings</h3>${d.bookings.map(b=>`<div class="booking"><div><b>${esc(b.spaceName)}</b><div class="muted">${esc(b.date)} · ${esc(b.startTime)}–${esc(b.endTime)}</div></div><span class="status">${esc(b.status)}</span></div>`).join("")||"<p>No bookings yet.</p>"}</div>`}catch(e){$("dash").innerHTML=`<div class="panel"><p>${esc(e.message)}</p></div>`}}
$("logoutBtn").onclick=()=>{user=null;localStorage.removeItem("workspaceHubUser");authUI();show("home");toast("Logged out")};["search","kind","capacity"].forEach(id=>$(id).addEventListener("input",renderSpaces));load();authUI();
