import crypto from "node:crypto";import express from "express";import cors from "cors";import dotenv from "dotenv";import bcrypt from "bcryptjs";import jwt from "jsonwebtoken";import mongoose from "mongoose";
dotenv.config();const app=express();app.use(cors());app.use(express.json());const PORT=process.env.PORT||5000,SECRET=process.env.JWT_SECRET||"dev_secret_change_me";
const userSchema=new mongoose.Schema({name:String,email:{type:String,unique:true},passwordHash:String},{timestamps:true});const spaceSchema=new mongoose.Schema({name:String,city:String,kind:String,capacity:Number,features:[String],pricePerHour:Number},{timestamps:true});const bookingSchema=new mongoose.Schema({spaceId:mongoose.Schema.Types.ObjectId,userId:mongoose.Schema.Types.ObjectId,date:String,startTime:String,endTime:String,status:{type:String,default:"confirmed"}},{timestamps:true});
const User=mongoose.model("User",userSchema),Space=mongoose.model("Space",spaceSchema),Booking=mongoose.model("Booking",bookingSchema);let db=false;
let memUsers=[],memSpaces=[{_id:"s1",name:"Focus Desk A12",city:"Guwahati",kind:"Desk",capacity:1,features:["Wi-Fi","Monitor","Power"],pricePerHour:120},{_id:"s2",name:"Brahmaputra Meeting Room",city:"Guwahati",kind:"Meeting Room",capacity:8,features:["Display","Whiteboard","Video call"],pricePerHour:850},{_id:"s3",name:"Hillside Private Office",city:"Shillong",kind:"Private Office",capacity:4,features:["Wi-Fi","AC","Coffee"],pricePerHour:500},{_id:"s4",name:"Riverfront Team Room",city:"Tezpur",kind:"Meeting Room",capacity:4,features:["Display","Wi-Fi"],pricePerHour:600}],memBookings=[];
mongoose.connect(process.env.MONGODB_URI||"").then(()=>{db=true;console.log("MongoDB connected")}).catch(()=>console.log("MongoDB unavailable; using memory mode"));
const token=u=>jwt.sign({id:String(u._id)},SECRET,{expiresIn:"7d"}),safe=u=>({id:String(u._id),name:u.name,email:u.email,token:token(u)});
async function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch{res.status(401).json({message:"Authentication required"})}}
async function getUser(id){return db?User.findById(id):memUsers.find(x=>String(x._id)===String(id))}
app.get("/api/health",(q,r)=>r.json({status:"ok",database:db?"mongodb":"memory"}));
app.post("/api/auth/register",async(q,r)=>{try{let{name,email,password}=q.body;if(!name||!email||!password)return r.status(400).json({message:"Name, email and password are required"});let ex=db?await User.findOne({email}):memUsers.find(x=>x.email===email);if(ex)return r.status(409).json({message:"Email already registered"});let u={name,email,passwordHash:await bcrypt.hash(password,12)};let x=db?await User.create(u):Object.assign({_id:crypto.randomUUID()},u);if(!db)memUsers.push(x);r.status(201).json({user:safe(x)})}catch(e){r.status(500).json({message:e.message})}});
app.post("/api/auth/login",async(q,r)=>{try{let{email,password}=q.body,u=db?await User.findOne({email}):memUsers.find(x=>x.email===email);if(!u||!(await bcrypt.compare(password,u.passwordHash)))return r.status(401).json({message:"Invalid email or password"});r.json({user:safe(u)})}catch(e){r.status(500).json({message:e.message})}});
app.get("/api/spaces",async(q,r)=>{try{r.json(db?await Space.find().sort({createdAt:-1}):memSpaces)}catch(e){r.status(500).json({message:e.message})}});
app.post("/api/bookings",auth,async(q,r)=>{try{let{spaceId,date,startTime,endTime}=q.body;if(!spaceId||!date||!startTime||!endTime)return r.status(400).json({message:"All booking fields are required"});if(startTime>=endTime)return r.status(400).json({message:"End time must be after start time"});let clash=db?await Booking.findOne({spaceId,date,status:"confirmed",$or:[{startTime:{$lt:endTime},endTime:{$gt:startTime}}]}):memBookings.find(b=>b.spaceId===spaceId&&b.date===date&&b.status==="confirmed"&&b.startTime<endTime&&b.endTime>startTime);if(clash)return r.status(409).json({message:"Space is already booked for that time"});let b={spaceId,userId:req.user.id,date,startTime,endTime,status:"confirmed"};let x=db?await Booking.create(b):Object.assign({_id:crypto.randomUUID()},b);if(!db)memBookings.push(x);r.status(201).json(x)}catch(e){r.status(500).json({message:e.message})}});
app.get("/api/dashboard",auth,async(q,r)=>{try{let bs=db?await Booking.find({userId:req.user.id}).sort({date:1,startTime:1}):memBookings.filter(x=>x.userId===req.user.id);let out=[];for(let b of bs){let s=db?await Space.findById(b.spaceId):memSpaces.find(x=>x._id===b.spaceId);if(s)out.push({...b.toObject?.()||b,spaceName:s.name})}r.json({bookings:out})}catch(e){r.status(500).json({message:e.message})}});
app.listen(PORT,()=>console.log(`WorkspaceHub API running on http://localhost:${PORT}`));